package sad.hw1.dm.test;

import static org.junit.Assert.*;

import java.sql.SQLException;

import org.junit.Test;

import sad.hw1.domain.Contract;
import sad.hw1.domain.Product;
import sad.util.ApplicationException;
import sad.util.MfDate;
import sad.util.Money;

public class ContractTester {

	@Test
	public void testSaveOrUpdate() {
		Product p = new Product("Word Proc 2014", "W", null);
		Contract c = new Contract(p, new Money(1000.50), new MfDate(2014, 1, 28));
		long autoGeneratedId = -1;
		try {
			autoGeneratedId = c.saveOrUpdate();
		} catch (SQLException | ApplicationException e) {
			e.printStackTrace();
		}
		assertTrue(autoGeneratedId > 0);
		
		c.setRevenue(new Money(100.50));
		c.setWhenSigned(new MfDate(2014, 1, 29));
		long retId = -1;
		try {
			retId = c.saveOrUpdate();
		} catch (SQLException | ApplicationException e) {
			e.printStackTrace();
		}
		assertTrue((retId > 0) && (retId == autoGeneratedId));
	}
	
	@Test
	public void testDelete()
	{
		Product p = new Product("Word Proc 2014", "W", null);
		Contract c = new Contract(p, new Money(1000.50), new MfDate(2014, 1, 28));
		long autoGeneratedId = -1;
		try {
			autoGeneratedId = c.saveOrUpdate();
		} catch (SQLException | ApplicationException e) {
			e.printStackTrace();
		}
		long deletedId = -1;
		try {
			deletedId = c.delete();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		assertEquals(autoGeneratedId, deletedId);
	}

}
